### ISSUE TITLE
ByteBoundedQueue performance issues in high concurrency scenarios

### ISSUE THREAD

**Issue by heavenyunyou** [openzipkin/zipkin-reporter-java#101]
I am using zipkin-reporter-0.7.0.jar and I have a performance issue.
I use tomcat to build a simple web project. First of all, I tested the request baseline time in the high concurrency scenario. In a scenario where **10,000 requests are concurrent**, the average time per request is about **20-60** us.
Then we use brave for tracking. We initialized **AsyncReporter** when the web project started. Then I try to send 10000 requests in parallel. The result of the test is very unstable. The request can take up to **900ms** and the minimum is about 330us. I re-tested several times and found that the results were not the same, sometimes up to 500ms, sometimes only 500us.
I guess it is due to a lock problem. I saw ReentrantLock in the **offer** method of **ByteBoundedQueue.java**. My test discovery is indeed a performance issue caused by ReentrantLock. And in the latest version, the lock still exists.
How can the interface performance be guaranteed under high concurrency scenarios?

**Comment by heavenyunyou** [comment]
We are using v3 version of brave. The package is github/kristofa/brave. So there will be a lot of work to do to upgrade the brave & zipkin-reporter verison in our project. Is there any solutions in v3 version?

**Comment by adriancole** [comment]
the brave 3 packages were released for quite a while (even though version
numbers went past 3), and retrofitted to zipkin reporter v2 iirc. maybe
move to the latest release of that?

https://search.maven.org/#artifactdetails%7Cio.zipkin.brave%7Cbrave-core%7C4.13.4%7Cjar

**Comment by adriancole** [comment]
closing as it is relating to a long unreleased version. feel free to re-open
