### ISSUE TITLE
OkHttp Reporter throws IllegalStateException on server failure, timeout, etc shutting down asyncreporter thread

### ISSUE THREAD

**Issue by unintended** [openzipkin/zipkin-reporter-java#108]
asyncReporter initialization:
```(java)
AsyncReporter.builder(OkHttpSender.create(zipkinEndpoint))
                    .build();
```
In AsyncReporter code we have a special handling of IllegalStateException (meaning sender was unexpectedly closed by another thread), rethrowing it:
https://github.com/openzipkin/zipkin-reporter-java/blob/932533401c637b2bc313ccda830366c98cec5cb8/core/src/main/java/zipkin2/reporter/AsyncReporter.java#L291

The problem is that IllegalStateException is also throwed by reporter for invalid server responses at:
https://github.com/openzipkin/zipkin-reporter-java/blob/932533401c637b2bc313ccda830366c98cec5cb8/okhttp3/src/main/java/zipkin2/reporter/okhttp3/HttpCall.java#L92

So when OkHttpSender receives invalid server response, the exceptions is raised to the async reporter thread shutting it down. So, if server failed to respond (e.g. my http balancer in front of zipkin server returns "backend timeout" message in case when zipkin is down or restarting), the whole reporter thread is shutting down and stops sending spans at all (but normally it's expected to skip and try to send next spans).

My proposal: not to use IllegalStateException as marker for out-of-band closed senders and make a special exception class for such case, handling it properly in flush() method. There are many more potential places where IllegalStateException can be raised in senders, so it's not a proper way to relay in this exception type.

Trace log:
```
ERROR 2018-05-10 20:22:04,845 [AsyncReporter{OkHttpSender{https://***/api/v2/spans}}] Thread
 AsyncReporter{OkHttpSender{https://***/api/v2/spans}} finished with error
java.lang.IllegalStateException: response for Request{method=POST, url=https://***/api/v2/spans, tag=null} failed: Backend timeout

        at zipkin2.reporter.okhttp3.HttpCall.parseResponse(HttpCall.java:93)
        at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:35)
        at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:26)
        at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:272)
        at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:179)
```

**Comment by adriancole** [comment]
I see what you mean.

**Comment by adriancole** [comment]
Question though.. can you qualify what you mean by "There are many more potential places where IllegalStateException can be raised in senders"?

I'm not sure it is completely open ended as you suggest. For example, we can solve the scenario you mentioned simply by changing the invalid server response to a normal RuntimeException. I think the bug is that we used ISE in the OkHttpSender for the server response (it is not the right exception). I think the ISE is the correct exception to throw for a state machine error, such as using something after it is in closed state.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-reporter-java/pull/110 I think will handle this unless it doesn't :)

I prefer this approach as it doesn't require us to create an exception type.
