### ISSUE TITLE
Move repository to https://github.com/apache/incubator-zipkin-reporter-java

### ISSUE THREAD

**Issue by michaelsembwever** [openzipkin/zipkin-reporter-java#122]
As part of the move to the Apache Software Foundation this repository will transfer ownership to `apache` and name to `incubator-zipkin-reporter-java`.

See https://issues.apache.org/jira/browse/INFRA-16989

**Comment by jeqo** [comment]
Closing as https://issues.apache.org/jira/browse/INFRA-18604
