### ISSUE TITLE
Add TLS support for UrlConnectionSender

### ISSUE THREAD

**Issue by falenn** [openzipkin/zipkin-reporter-java#123]
As a developer, I want to leverage [OpenCensus-Java](https://github.com/census-instrumentation/opencensus-java) [ZipkinExporter](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporter.java) for distributed trace emissions at nominal, sampled rate with little, added infrastructure, yet I have a requirement to do so over untrusted networks.  I need the UrlConnectionSender to support TLS.

Consider adding TLS support for [URLConnectionSender](https://github.com/openzipkin/zipkin-reporter-java/blob/master/urlconnection/src/main/java/zipkin2/reporter/urlconnection/URLConnectionSender.java).  Not all elements of a distributed system reside within an enclave nor are considered to have trusted communications by being within an enclave.  TLS support will enable distributed services the opportunity to consolidate tracing across untrusted networks without adding another architectural element such as a message broker.

One such way to accomplish this is to add  a TLSURLConnectionSender or modify URLConnectionSender to use a builder pattern, allowing the developer or upstream consumer to supply the SSLContext.
For example, I have composed an example implementation for a TLSURLConnectionSender, allowing the developer to supply their own SSLContext as such:
```
public final class TLSURLConnectionSender extends sender {
    
    public static TLSURLConnectionSender create(String endpoint) {
        return newBuilder().endpoint(endpoint).build();
    }
    
    public static Builder newBuilder() {
        return new Builder();
    }

    public static final class Builder {
        SSLContext sslContext = null;
        
        Builder(TLSURLConnectionSender sender) throws SSLException {
            this.endpoint = sender.endpoint
            ...
            if(sender.sslContext != null) {
                sslContext = sender.sslContext;
            else {
                this.sslConext = SSLContextHelper.getDefaultContext();
            }
        }
        ...
        public Builder sslContext(SSLContext sslContext) {
            this.sslContext = sslContext;
        }
        ...
```
   
In this example, the developer can supply an SSLContext or through a SSLContextHelper aid the developer in constructing a default context.  The default context would leverage java.util.properties object instance supplied in using the common javax.net.ssl.* properties for setting keystore and truststore information.

Allowing the developer to supply their own SSLContext does, however, motivate a change to the way upstream construction occurs. Modifying URLConnectionSender or creating a TLSURLConnectionSender option allowing the developer to supply a SSLContext does, for example, change the contract for creation with the [ZipkinExporter](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporter.java).  Moving to a builder places all configurations in the hands of the developer at the time of creation.  [OpenCensus-Java](https://github.com/census-instrumentation/opencensus-java) would need to consider adoption of a builder contract for the ZipkinExporter in order to allow the developer to supply SSLContext needs for the downstream (TLS)URLConnectionSender use.  The practice of using a builder is not foreign to OpenCensus - the SpanBuilder among other classes uses a builder approach creation.

**Comment by adriancole** [comment]
I would add this to the existing builder, with some state checks.

I would recommend adding fields for SSLSocketFactory and HostnameVerifier like done in feign except using builder (this code was almost zero maintenance) https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Client.java#L74

Some relevant tests are here https://github.com/OpenFeign/feign/blob/master/core/src/test/java/feign/client/DefaultClientTest.java

Also, recently okhttp has extra features for mock TLS so probably you can re-use some of those more modern fixtures in your tests such as we do here: https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchStorageTest.java#L105

**Comment by falenn** [comment]
Thanks!  This work could continue for sake of completeness, but if OkHTTPSender now supports TLS, should URLConnectionSender continue?

**Comment by adriancole** [comment]
URLConnectionSender has no dependencies, so it should persist. though it is true that if folks are fine using okhttp this can wait until it is not the case

**Comment by jalexsir** [comment]
Hi @codefromthecrypt.
I want to use URLConnectionSender but this class doesn't support HTTPS and SSLContext. And I can't extend from URLConnectionSender because this is final. zipkin-sender-okhttp3 is not supported by my system, because dependence com.squareup.okhttp3 » okhttp is not bundle.
How I can solve this problem? 
Thank you!

**Comment by codefromthecrypt** [comment]
okhttp from zipkin packaging is a bundle. you can look at this https://github.com/openzipkin/zipkin-reporter-java/blob/master/okhttp3/bnd.bnd as well projects like https://github.com/openzipkin/brave-karaf/blob/3f2452744b09bd2f915cce7a401c53bf3bceb3bc/features/src/main/resources/features.xml#L41-L50 that use it

Java's TLS config can be done in ways done by java. Then, there's the idea that someone could raise a PR to complement that.

ex.
```java
if (connection instanceof HttpsURLConnection) {
        HttpsURLConnection sslCon = (HttpsURLConnection) connection;
        if (sslContextFactory != null) {
          sslCon.setSSLSocketFactory(sslContextFactory);
        }
        if (hostnameVerifier != null) {
          sslCon.setHostnameVerifier(hostnameVerifier);
        }
      }
```

These sorts of requests start adding together as there are co-related things. This would probably lead to maintainers desiring a builder and optional opt-in to these things. 

However, if all you need is to use okhttp with osgi, that's already done in other projects. Meanwhile, I'm not currently a maintaining this project personally. no need to mention me personally as I'm not active at the moment. I won't be implementing this personally or following up. However, i hope this guidance helps!

**Comment by falenn** [comment]
@codefromthecrypt Thanks for your help!  I think I ended up cloning and changing to a builder pattern like you mentioned to get the functionality I needed, so right on!
