### ISSUE TITLE
How to trace database requests to mongoDB

### ISSUE THREAD

**Issue by rekaparathalwar** [openzipkin/zipkin-reporter-java#125]
Do you have any tools built to trace requests to MongoDB? I could see that you are supporting Http, Thrift, Memcache, SQL and Redis requests.

Does Zipkin support tracing for MongoDB? If yes, can you please point me to any examples. I couldn't find anything on the internet. If not, do you have any plans to support MongoDB?

**Comment by devinsba** [comment]
@rekaparathalwar questions of this nature are best handled by us at https://gitter.im/openzipkin/zipkin

If you are looking for a feature request https://github.com/openzipkin/brave is where you want to be
