### ISSUE TITLE
encoding bug in okhttp3 sender 1.1.2

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-reporter-java#133]
https://github.com/openzipkin/zipkin-reporter-java/blob/1.1.2/okhttp3/src/main/java/zipkin/reporter/okhttp3/RequestBodyMessageEncoder.java#L64 is a bug. it is using code 11 instead of 12 for struct https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java#L35

This was identified here https://github.com/bizreach/play-zipkin-tracing/pull/42

**Comment by shakuzen** [comment]
Is the plan to make a new patch release for 1.1.x then?

**Comment by adriancole** [comment]
yeah I will but it would only help mostly with a  recut of old brave. the whole process will take a couple days, so I am deferring that :P

**Comment by adriancole** [comment]
closing as no one else asked for a backport in a year's time
