### ISSUE TITLE
InMemoryReporterMetrics.messagesDropped causes out of memory

### ISSUE THREAD

**Issue by stengvac** [openzipkin/zipkin-reporter-java#139]
Hello,

when application which has incorrectly set server where metricts should be send, try to send metrict, then  every time UnknownHostException (or similiar exception) is stored by calling 
`
     zipkin2.reporter.InMemoryReporterMetrics#incrementMessagesDropped()
`
. This method place throwable into instance variable `
messagesDropped`, which is never cleared so can only grow in size. `messgesDropped` is HashMap and as key is used exception instance, which has different hashCode for each instance.

Meaby method `
InMemoryReporterMetrics#clear()
` should probably also clear this collection. Or use different key generator.

**Comment by devinsba** [comment]
This was fixed about 9 months ago: https://github.com/openzipkin/zipkin-reporter-java/pull/119 and released in `2.7.7`

Please update to the latest version and let us know if that doesn't fix the issue
