### ISSUE TITLE
Reduce default message size

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-reporter-java#153]
In docker testing, the default message size of 5MiB is too much.. it basically makes elasticsearch fall over. I think we should reduce significantly lower, like 1000000 bytes (kafka's size) or lower than that.

cc @anuraaga

**Comment by jeqo** [comment]
Similar to elasticsearch issue, if we ingest from different transports to same storage (e.g. via forwarder) we will end up having issues as different senders default message size disparity. I'm getting similar issues operating https://github.com/openzipkin-contrib/zipkin-storage-kafka as HTTP batches can be 1.2MB, breaking Kafka pipeline.

I'd like to propose 500KB as default for all transports, as half of Kafka default max message size is the lowest default (1MB).

cc @jorgheymans @anuraaga

**Comment by jorgheymans** [comment]
Makes sense, is this a breaking change in a way ?

**Comment by jeqo** [comment]
@jorgheymans I do not see any breaking change. As we batch by size based on spans, and we haven't see any span bigger than 500KB, we should be fine releasing this.
