### ISSUE TITLE
The initialization of bean `zipkinReporter` generates Kafka warnings

### ISSUE THREAD

**Issue by ferblaca** [openzipkin/zipkin-reporter-java#169]
Artifact: _io.zipkin.reporter2:zipkin-sender-kafka:2.10.3_

By default, when the `kafkaSender` bean is initialized in the `ZipkinKafkaSenderConfiguration` configuration class, the following properties are loaded when _`KafkaSender.newBuilder()`_ is invoked:

```
properties = {Properties@9280}  size = 5
 "max.request.size" -> {Integer@9289} 1000000
 "value.serializer" -> "org.apache.kafka.common.serialization.ByteArraySerializer"
 "batch.size" -> {Integer@9293} 0
 "acks" -> "0"
 "key.serializer" -> "org.apache.kafka.common.serialization.ByteArraySerializer"
```

 After, in the initialization of the bean `zipkinReporter` of the configuration class `ZipkinAutoConfiguration`, the method _`checkResult(asyncReporter)`_ ends up invoking the creation of the `AdminClient` with the same properties of the `KafkaSender` (adding the "bootstrap.servers" property) :

_zipkin2.reporter.kafka.KafkaSender.java_

```
   AdminClient getAdminClient() {
    if (adminClient == null) {
      synchronized (this) {
        if (adminClient == null) {
          adminClient = AdminClient.create(properties);
        }
      }
    }
    return adminClient;
  }
```
Where the properties are:
```
properties = {Properties@9787}  size = 6
 "batch.size" -> {Integer@9293} 0
 "acks" -> "0"
 "bootstrap.servers" -> "localhost:9092"
 "key.serializer" -> "org.apache.kafka.common.serialization.ByteArraySerializer"
 "max.request.size" -> {Integer@9289} 1000000
 "value.serializer" -> "org.apache.kafka.common.serialization.ByteArraySerializer"
```

The same properties are being used in the configuration of the `KafkaSender` and the `AdminClient`. We think this is not correct.

This causes them to always show console alerts:

	2020-02-19 15:47:11,269 [pool-3-thread-1] WARN  org.apache.kafka.clients.admin.AdminClientConfig -  The configuration 'max.request.size' was supplied but isn't a known config.
	2020-02-19 15:47:11,269 [pool-3-thread-1] WARN  org.apache.kafka.clients.admin.AdminClientConfig -  The configuration 'value.serializer' was supplied but isn't a known config.
	2020-02-19 15:47:11,269 [pool-3-thread-1] WARN  org.apache.kafka.clients.admin.AdminClientConfig -  The configuration 'batch.size' was supplied but isn't a known config.
	2020-02-19 15:47:11,269 [pool-3-thread-1] WARN  org.apache.kafka.clients.admin.AdminClientConfig -  The configuration 'acks' was supplied but isn't a known config.
	2020-02-19 15:47:11,269 [pool-3-thread-1] WARN  org.apache.kafka.clients.admin.AdminClientConfig -  The configuration 'key.serializer' was supplied but isn't a known config.

**Comment by jeqo** [comment]
Thanks @ferblaca. 

Are the `warn` logs the only issue here? Or do you have a functional requirement to have different property set exposed for `Admin` (e.g. different keystore, etc)?

I'd say that sharing properties on the same application is a common practice usually (check logs on schema-registry or connectors, they have similar logs), as not only `bootstrap.servers` is the same but other security configs as well. If we become picky on what to take from producer to admin configs we will need to maintain that list if it changes in future version. Does it make sense?

**Comment by ferblaca** [comment]
Hi,

Would you consider the following pull request?
https://github.com/openzipkin/zipkin-reporter-java/pull/170

The goal is not to generate WARN logs for the creation of Kafka's admin client, because now the same properties of the producer are used as for the admin client.

We have added the "adminClientProperties" Properties and "overridesAdminClient" methods, which will be used to optionally set specific properties for kafka's admin client. For example:

```
Map<String, String> adminClientProperties = new LinkedHashMap<>();
adminClientProperties.put(AdminClientConfig.RETRIES_CONFIG, "5");

KafkaSender kafkaSender = KafkaSender.newBuilder().topic(this.topic)
    .overrides(properties)
    .overridesAdminClient(adminClientProperties)
    .build();
```


In the creation of the "KafkaSender" with the builder, the "adminClientProperties" properties are the result of the filtered producer settings (removing those properties that do not appear in kafka's AdminClientConfig) + the properties added specifically for the admin client (overrridesAdminClient).

This way, admin client will use at least the same properties configured for the producer, such as security settings, but removing those that are producer-specific.

When the "getAdminClient" method is invoked, the resulting properties specified in the "AdminClientProperties" will be used.

```
  AdminClient getAdminClient() {
    if (adminClient == null) {
      synchronized (this) {
        if (adminClient == null) {
          adminClient = AdminClient.create(adminClientProperties);
        }
      }
    }
    return adminClient;
  }
```

**Comment by adriancole** [comment]
going out in 2.12.3
