### ISSUE TITLE
Using the OkHttpSender with basic auth 

### ISSUE THREAD

**Issue by DarwinSin** [openzipkin/zipkin-reporter-java#177]
I am attempting to use the OKHttpSender with basic authentication, following the steps on the java doc.  The .clientBuilder().authenticator(myAuthenticator).build() returns me an OKHttpClient, but the OKHttpSender has no public constructor or builder to pass in this authenticated client . How do I go about implementing a span sender with authenticator.

**Comment by codefromthecrypt** [comment]
@DarwinSin you shouldn't call build on the clientBuilder(). just add the authenticator..

ex senderBuilder = OKHttpSender.builder...
senderBuilder.clientBuilder().authenticator(myAuthenticator);
sender = senderBuilder.build();
