### ISSUE TITLE
Zipkin AsyncReporter is not blocking on close

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/zipkin-reporter-java#202]
## Feature
Allow the `AsyncReporter.close()` to be properly used in shutdown hooks.

## Rationale
Currently when a e.g. batch job finishes the `AsyncReporter`, even if registered as a shutdown hook, does not drain the span queue in a blocking way. The current solution is to do sth more or less as presented here [1] . So first, call `flush`, then wait for the timeout period + some time required to send out spans and only then call `close`. It would be great to have `close()` do all of that in a blocking way.

## Example Scenario
Each application using an `AsyncReporter`.

## Prior Art
* [1] https://github.com/spring-cloud/spring-cloud-sleuth/pull/2036/files#diff-36ecfac59e4fa2cf4943436b9402d46508965320fb013f97da12a5d7817392c1R138-R152

**Comment by shakuzen** [comment]
Looking at the code, it looks like it does wait up to the `closeTimeout` for spans to be flushed when closing:

https://github.com/openzipkin/zipkin-reporter-java/blob/ab669b823ab2ccbb753c4005247090c0645c6d5b/core/src/main/java/zipkin2/reporter/AsyncReporter.java#L340-L343

Is that not the behavior you're seeing?
