### ISSUE TITLE
C

### ISSUE THREAD

**Issue by Djwszone** [openzipkin/zipkin-reporter-java#206]
## Describe the Bug
A clear and concise description of what the bug is. If you have a solution in mind, skip raising an issue and open a pull request instead.

Regardless, the best is to spend some time to write a failing test. Bugs with tests get fixed and stay fixed.

## Expected Behaviour
Suggest what you think correct behaviour should be. Note, it may be solved differently depending on the problem.

**Comment by shakuzen** [comment]
This appears to have been opened in error. If you have an issue to report, please provide a title and the requested information in the issue template.
