### ISSUE TITLE
Add support for OTLP format

### ISSUE THREAD

**Issue by jonatan-ivanov** [openzipkin/zipkin-reporter-java#209]
I'm not sure if this is the right repo for this issue (please transfer to a better place if any). 

## Feature
Add support for publishing spans using [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) (OpenTelemetry Line Protocol) format.

## Rationale
There are users who like to use Brave but they want to use a backend that supports OTLP format (not necessarily Zipkin format). Right now (as far as I know) they have two options:
1. Use the OTel collector and let it convert the data from Zipkin's format to OTLP (this needs extra infrastructure).
2. Migrate to the OTel SDK (or use Micrometer Tracing/Sleuth-OTel but they also use the OTel SDK). 

Since the [OTLP specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) is stable now, it opens the door for other libraries to publish data in OTLP format.

## Example Scenario
This would enable users to use Brave with a backend that supports OTLP format (but does not necessarily support Zipkin format) and would not force them to migrate to OTel or add extra component in their infrastructure (OTel Collector).

## Prior Art
I'm not really aware of any that would be similar.
The OTel Collector can be slightly related since it [can receive data in the Zipkin format](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/zipkinreceiver) and convert it. Or Micrometer's [OtlpMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/671803a612b721b2dbfd29db04b05263c0bf83fa/implementations/micrometer-registry-otlp/src/main/java/io/micrometer/registry/otlp/OtlpMeterRegistry.java) that can emit metrics data in OTLP format. Neither of them are really connected.

**Comment by basvanbeek** [comment]
Yes if this is really desired than a new reporter project would make more sense, but would need a sponsor to create and maintain it. 

By the way, OTel collector really is meant for these kind of conversions as well as being able to upstream data to central collection in case of multi cluster environments. It is fairly normal for OTel ecosystems to have OTel collectors installed. Zipkin import is pretty much always enabled in vendor distributions of OTel.

**Comment by marcingrzejszczak** [comment]
> By the way, OTel collector really is meant for these kind of conversions as well as being able to upstream data to central collection in case of multi cluster environments. It is fairly normal for OTel ecosystems to have OTel collectors installed. Zipkin import is pretty much always enabled in vendor distributions of OTel.

I agree, the problem is that people have problems with using Brave and not being able to export in OTLP format. There are certain vendors that only started to accept OTLP format of traces :shrug:

**Comment by jonatan-ivanov** [comment]
>By the way, OTel collector really is meant for these kind of conversions as well as being able to upstream data to central collection in case of multi cluster environments. It is fairly normal for OTel ecosystems to have OTel collectors installed. Zipkin import is pretty much always enabled in vendor distributions of OTel.

As far as I know, the OTel community has issues with maintaining Zipkin-related components (no code owner). Also, a lot of users do not want an extra component in their infrastructure only to convert data from one format to the other. That's why the OTel SDK has a Zipkin exporter and it does not force users to use the collector. This choice is not available with Brave right now, either users don't use Brave or they use the collector.

**Comment by jcchavezs** [comment]
We do have code owners but zipkin is and always was a volunteering project
and currently owners don't have capacity to volunteer it.

**Comment by jonatan-ivanov** [comment]
I'm talking about Zipkin-related components in OTel, not Zipkin itself. A few months ago, [in a comment on an issue in opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16530#issuecomment-1485738325), I was told that
>we don't have Zipkin code owners in this repository

and

>We do not have code owners for the Zipkin exporter/receiver/translator, and none of the current maintainers of this repository are Zipkin experts, from what I know.

I thought this is still the case.

**Comment by basvanbeek** [comment]
Since Zipkin-Reporter-Java already supports a multitude of exporters using different protocols I, after some thoughts, see no issue with supporting OLTP within this repository.

**Comment by codefromthecrypt** [comment]
ps to the point of zipkin already doing things, we only support zipkin protocols. we actually don't support anything defined externally in another org, except in different repos. It is probably easy to conflate transports like Kafka, used and defined by zipkin sites and in the zipkin org, from formats not defined or influenceable from here.

**Comment by codefromthecrypt** [comment]
opened https://github.com/openzipkin-contrib/zipkin-otel to carry any of this forward. I can't personally assist, but perhaps other committers in support of this can review and/or grant karma to let folks make something like zipkin-gcp except for otel stuff!
