### ISSUE TITLE
Test scope for io.zipkin.java:zipkin:test-jar

### ISSUE THREAD

**Issue by kenfinnigan** [openzipkin/zipkin-reporter-java#28]
When I have a dependency on zipkin-sender-urlconnection it dependency manages in io.zipkin.java:zipkin:test-jar as compile scope.

As the dependency uses a different package type, it's not possible to exclude that dependency with Maven.

Should the dependency be in test scope, so as not to bring it in at compile time?

**Comment by adriancole** [comment]
yeah that's a bug (surprised it lingered so long)!

mind fixing it?

https://github.com/openzipkin/zipkin-reporter-java/blob/master/pom.xml#L163

**Comment by kenfinnigan** [comment]
Not a problem, wanted to make sure it was a bug first!
