### ISSUE TITLE
Is flush non-blocking?  How to ensure all spans are cleared?

### ISSUE THREAD

**Issue by dangets** [openzipkin/zipkin-reporter-java#29]
I am instrumenting a manually invoked jar and I am having troubles getting the traces to consistently show up.  I am explicitly calling `Reporter.flush()` before exiting.  I find that if I debug and give the app more time I am able to see the trace, but running normally I usually don't end up getting the entire trace.

Is there a blocking version of flush that I can use?

I _could_ use an `InMemoryReporterMetrics` and check the `queuedSpan` count, but this seems kind of hacky.

**Comment by adriancole** [comment]
Correct. at the moment, when you close() the reporter, it blocks until the
last batch was sent, but the actual call to the sender is async. We could
adjust the code that when you call asyncReporter.close() block until the
sender operation succeeds or fails. Sound good?

**Comment by adriancole** [comment]
well I suppose that or make a flag which when set any call to flush is
blocking (regardless of if the flush is manual or automatic)..

**Comment by dangets** [comment]
Either way would work ... could it be a different builder option on the AsyncReporter like `flushSenderOnClose(boolean b)` or is that too specific to this situation? ... that may be what you were getting at with your first suggestion.

**Comment by adriancole** [comment]
first suggestion was really to change the close() behavior as opposed to making a flag. close is already a blocking op

**Comment by dangets** [comment]
Again, I'm good with either - do you have a preference?  I could try implementing if you'd like.

**Comment by adriancole** [comment]
Why don't you give it a try!

here's some hints..

```java
    /** When true, calls to {@link #flush()} block until send operations complete. Default false */
    public Builder blockOnSend(boolean blockOnSend) {
      this.blockOnSend = blockOnSend;
      return this;
    }

...

        if (blockOnSend) {
          AwaitableCallback blockingCallback = new AwaitableCallback();
          sender.sendSpans(nextMessage, blockingCallback);
          blockingCallback.await(); // will propagate on exception
        } else {
          sender.sendSpans(nextMessage, failureCallback);
        }
```

Note that testing will be tricky. Also, whether or not we block, there still could be spans left in the queue which default behavior drops. For example, you could look at the close impl to try to clear it up to a specific timeout (or just assume all is ok)

**Comment by dangets** [comment]
I added the code blocks you suggested, but am having some difficulty writing the tests.  In digging more into the code, I'm getting more confused why I had the original problem.

I am using the `URLConnectionSender` and the docs for [`sendSpans`](https://github.com/openzipkin/zipkin-reporter-java/blob/ed79b27646180c57605af0e4a32ce0b8b2a88f52/urlconnection/src/main/java/zipkin/reporter/urlconnection/URLConnectionSender.java#L131) says it sends the POST asynchronously, but I don't see where the async is happening.  I suppose with the connection output stream, messages could be getting buffered and lost when the JVM exits - but otherwise it looks synchronous.

If the `URLConnectionSender` is synchronous, then externally calling `Reporter.flush` should block.  Is it because the messages are sent in batches and only whatever can fit into the last batch gets flushed?

I could see if the `Sender.sendSpans` implementation was asynchronous, then the original problem would pop up.

I'll continue to see if I can get reliable unit tests added and then do the pr.  Thanks!

**Comment by adriancole** [comment]
>
> I am using the URLConnectionSender and the docs for sendSpans
> <https://github.com/openzipkin/zipkin-reporter-java/blob/ed79b27646180c57605af0e4a32ce0b8b2a88f52/urlconnection/src/main/java/zipkin/reporter/urlconnection/URLConnectionSender.java#L131>
> says it sends the POST asynchronously, but I don't see where the async is
> happening. I suppose with the connection output stream, messages could be
> getting buffered and lost when the JVM exits - but otherwise it looks
> synchronous.
>
sorry that's a c&p doc bug. certainly URLConnectionSender is synchronous,
just that its results are callbacks vs a return type.

> If the URLConnectionSender is synchronous, then externally calling
> Reporter.flush should block. Is it because the messages are sent in
> batches and only whatever can fit into the last batch gets flushed?
>
yep sounds right. whatever couldn't fit into the batch would stay in the
buffer

> I could see if the Sender.sendSpans implementation was asynchronous, then
> the original problem would pop up.
>
> I'll continue to see if I can get reliable unit tests added and then do
> the pr. Thanks!
>
Maybe play with the stats to see what you're left with (for your original
problem) or pay close attention to the log message which would say if
something was dropped on close. good luck, I know it is a bit tricky, but
at least the sender being sync should help isolate it.

**Comment by adriancole** [comment]
ps there's now a control for how long to wait on close. regardless, order is close async reporter, then close sender
