### ISSUE TITLE
kafka update 0.10.0.0

### ISSUE THREAD

**Issue by ZhouZiHe** [openzipkin/zipkin-reporter-java#39]
Where should I notice if I want to user Kafka 0.10.0.0 API ?

**Comment by adriancole** [comment]
you'd want to make kafka10 module based on kafka08 except using most recent apis

**Comment by adriancole** [comment]
looks like we need to bump this in order to work with apps who use scala 2.12

wonder if it should be kafka 0.10 or if we need to do 0.9..

**Comment by adriancole** [comment]
actually we need to do minimum 0.10.2 for scala 2.12. Let's just do that as kafka10 (using latest api assuming it is compat between 0.10.2 and 3

https://issues.apache.org/jira/browse/KAFKA-4376
