### ISSUE TITLE
Improve name of AsyncReporter's flush thread

### ISSUE THREAD

**Issue by dgrabows** [openzipkin/zipkin-reporter-java#42]
The flush thread created by AsyncReporter uses a thread name that includes the toString() output of the sender (see https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin/reporter/AsyncReporter.java#L159). At least for the KafkaSender, this can result in very long thread names due to the inclusion of the Kafka producer configuration properties in KafkaSender's toString() output. In cases where the Kafka cluster being used requires TLS encryption or client authentication, inclusion of these properties in the thread name risks exposing sensitive configuration in log output.

Here is an example thread name I observed in logs using the 0.7.0 release and https://github.com/openzipkin/zipkin-reporter-java/blob/master/kafka10/src/main/java/zipkin/reporter/kafka10/KafkaSender.java as the sender. Some sensitive values have been replaced with placeholders.

```
AsyncReporter(KafkaSender{encoding=THRIFT, messageMaxBytes=1000000, encoder=THRIFT, topic=zipkin, properties={bootstrap.servers=192.168.0.1:9093,192.168.0.2:9093,192.168.0.3:9093, ssl.truststore.location=/not/a /real/path/trust.jks, acks=1, ssl.truststore.password=fakepassword, value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer, security.protocol=SSL, key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer}})
```

The length of the thread name makes reading or viewing logs awkward.

The inclusion of the value for ssl.truststore.password exposes information that should not be in logs. It is also not easy to excluded from log output, since thread name is generally useful and whether to include it in logs is often not configurable at the individual logger level.

Including properties is also redundant with the Kafka producer's logging. It will log it's configuration when the producer is created, replacing sensitive values with `[hidden]`.

Some possible ways to address this:
* Use the sender's class name in the thread name, instead of the sender's toString() output. This might reveal implementation details that could cause confusion, such as getting `AsyncReporter(AutoValue_KafkaSender)`, instead of `AsyncReporter(KafkaSender)`.
* Add a `String name();`, or similar, method to [Sender](https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin/reporter/Sender.java) and use the value returned from that method in the thread name. This gives senders control over how to identify themselves, but requires existing Sender implementations to be updated to be compatible (unless Java 8 default methods are an option).
* Exclude the `properties` field from KafkaSender's toString output. This addresses the sensitive data concern and helps with the length concern. Results would look something like `AsyncReporter(KafkaSender{encoding=THRIFT, messageMaxBytes=1000000, encoder=THRIFT, topic=zipkin})`.

Are there other options? Is there a way to address this that doesn't require changing the implementation of AsyncReporter, and possibly other components?

**Comment by adriancole** [comment]
I think we should tighten up the toString of the senders (including unit
tests for each with a comment of the impact)

**Comment by dgrabows** [comment]
I took at stab at this in #43. Let me know if that's what was intended.
