### ISSUE TITLE
Just run it independently on a server?

### ISSUE THREAD

**Issue by srkadiyala** [openzipkin/zipkin-reporter-java#48]
I have already brought up my Zipkin server as a service on Linux machine and hooked up MySQL database.

If I run now Zipkin reporter,

Will it automatically pick up the Spans in memory and push them to Kafka?
Where is the properties file in zipkin reporter that can be configured to input zipkin server host name and port, Kafka broker host name/port?
Where is the code you wrote to be placed?
Appreciate your inputs ...

**Comment by adriancole** [comment]
issues are for code changes, not Q/A please use gitter and don't raise issues unless a code change is needed

**Comment by adriancole** [comment]
mental note: we should copy this to the reporter repo so the advice is automatic via issue template like it is in other repositories https://github.com/openzipkin/zipkin/blob/master/.github/ISSUE_TEMPLATE.md
