### ISSUE TITLE
Broken shaded internal in kafka sender

### ISSUE THREAD

**Issue by hypnoce** [openzipkin/zipkin-reporter-java#61]
Bundled version of LazyCloseable in kafka-sender 1.0.2 is broken : 
```
...
   public void close() throws IOException {
      T maybeNull = this.maybeNull();
      if (maybeNull != null) {
         Util.checkArgument(maybeNull instanceof Closeable, "Override close() to close " + maybeNull, new Object[0]);
         ((Closeable)maybeNull).close();
      }
   }
...

```
In the close method, the Util class is not imported neither shaded in the jar. This leads to a ClassNotFoundException when calling this method.

**Comment by adriancole** [comment]
thanks will fix

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin/commit/1ec1e1be6385f8400e220d2c4b0b9bd010799fdd

will be sorted in zipkin 1.31.3 going out now sorry about that!

**Comment by hypnoce** [comment]
Just made a PR that fixes the issue. Hope that's what you had in mind.

**Comment by hypnoce** [comment]
Oh ok :) I see that you removed the usage of Util.

**Comment by adriancole** [comment]
>
> Oh ok :) I see that you removed the usage of Util.
>
yeah it was an oversight and this problem could bite other libraries, too..
Thanks for the shade fix, though!
