### ISSUE TITLE
[Bug] Kafka producer is not closed when kafka11 sender is closed

### ISSUE THREAD

**Issue by hypnoce** [openzipkin/zipkin-reporter-java#67]
Hi,

I realised that the kafka producer is no more a LazyCloseable. Therefore, the close method do not call the kafka producer close method and leaks into the Java MXBean registry.

I'll submit a test+fix soon.

Thanks

**Comment by adriancole** [comment]
Thanks! Ps in the future you can raise just the PR if raising a fix same day
