### ISSUE TITLE
manually publish 1.1.2 with JSR305 free zipkin dependency

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-reporter-java#74]
Our release scripts don't currently work on non-master builds cc @openzipkin/devops-tooling 

see https://github.com/openzipkin/brave/issues/451

**Comment by adriancole** [comment]
```bash
# commit that made 1.1.2-SNAPSHOT
git checkout cc26683be87560812ef244cdae9e37700f96ac12
git checkout -b 1.x
./mvnw versions:set -DnewVersion=1.1.2
# edit pom.xml and switch <tag>HEAD</tag> to <tag>1.1.2</tag>
git commit -am"1.1.2 release"
git push origin 1.x
git tag 1.1.2
git push origin 1.1.2

BINTRAY_USER=XXXX GH_USER=XXXX BINTRAY_KEY=XXXX GH_TOKEN=XXXX SONATYPE_USER=XXXX SONATYPE_PASSWORD=XXXX ./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -pl -:benchmarks -DskipTests -Dlicense.skip=true deploy

BINTRAY_USER=XXXX GH_USER=XXXX BINTRAY_KEY=XXXX GH_TOKEN=XXXX SONATYPE_USER=XXXX SONATYPE_PASSWORD=XXXX ./mvnw --batch-mode -s ./.settings.xml -nsu -N io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:sync

./mvnw versions:set -DnewVersion=1.1.3-SNAPSHOT
# edit pom.xml and switch <tag>1.1.2</tag> to <tag>HEAD</tag>
git commit -am"next snapshot"
git push origin 1.x
```

**Comment by abesto** [comment]
Hm, thought that's a plus? As in, continuous delivery breaks down once you start shipping releases of the same software from long-lived, non-synced branches. Of course while it's mostly a single person doing the releases this shouldn't be an issue.

Is this something you'd like to see changed?

**Comment by adriancole** [comment]
>
> Hm, thought that's a plus? As in, continuous delivery breaks down once you
> start shipping releases of the same software from long-lived, non-synced
> branches. Of course while it's mostly a single person doing the releases
> this shouldn't be an issue.
>
> Is this something you'd like to see changed?
>
I cut this because there was a bad dep and sometimes people can't change
code too fast. So far it is the only time ever having to have done this, so
just pinging for visibility not as a change is yet needed. The problem
would need to repeat a few times first :P Thanks for watching, though!
