### ISSUE TITLE
KafkaSender with kerberos auth

### ISSUE THREAD

**Issue by elgrado** [openzipkin/zipkin-reporter-java#75]
Is it possible to use KafkaSender to report to Kafka enabled with kerb auth?

**Comment by adriancole** [comment]
If that can be set via property overrides yes.. what configuration does
kerberos need?

**Comment by jeqo** [comment]
AFAIR, this question was answered on gitter. If there are still issues with this, please continue discussion in https://gitter.im/openzipkin/zipkin
