### ISSUE TITLE
header propogation to sender

### ISSUE THREAD

**Issue by neshdev** [openzipkin/zipkin-reporter-java#77]
I have a scenario where the Zipkin API endpoints are protected. The incoming request to the rest service usually has a cookie/token in the HttpServletRequest headers. Is it possible to access the HttpServletRequest object in the Sender class?

**Comment by adriancole** [comment]
>
> I have a scenario where the Zipkin API endpoints are protected. The
> incoming request to the rest service usually has a cookie/token in the
> HttpServletRequest headers. Is it possible to access the HttpServletRequest
> object in the Sender class?
>
this wouldn't be possible here as zipkin-reporter has no insight into
propagation. If you are using Brave, you could open an issue there as it is
possible to do such a thing.
