### ISSUE TITLE
Custom Kafka Topic

### ISSUE THREAD

**Issue by Ajeeshreloaded** [openzipkin/zipkin-reporter-java#80]
Hi, Is it possible to configure custom Kafka topic name instead of default "zipkin" Kafka topic using Spring XML configuration?

```
<bean id="sender" class="zipkin2.reporter.kafka11.KafkaSender" factory-method="create">
    <constructor-arg type="java.lang.String" value="BrokerHost"/>
</bean>
```

**Comment by adriancole** [comment]
This issue was moved to openzipkin/brave#549

**Comment by adriancole** [comment]
moved as the spring support is actually in the brave project
