### ISSUE TITLE
Add a disruptor based async reporter

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-reporter-java#81]
We can calculate the size of a span without serializing it. We should be able to make an async reporter that defers serialization, but still allows us to drop spans that are too big to send. It should be fun work, if someone's up to it.

We could also consider making this disruptor based, or otherwise with a fancier ringbuffer opt-in given a dep like https://github.com/real-logic/agrona.

**Comment by wu-sheng** [comment]
In SkyWalking, we put the Spans(actually Segment) into a ringbuffer, then consume it, finally send it. So I agree with you, defer serialization is a good idea. 

For the ringbuffer, [LMAX-Exchange/disruptor](https://github.com/LMAX-Exchange/disruptor) is really a good project. For SkyWalking, we use a array based queue, implement by ourself.

**Comment by adriancole** [comment]
Deferring serialization does help, but there's likely more to be saved by changing how the buffer works. Since our encoders are pretty good, we only save a few microseconds by deferring encoding:

There are brave's end-to-end benchmarks:

```
Benchmark                                           Mode  Cnt    Score    Error  Units
EndToEndBenchmarks.server_get                       avgt   15  133.966 ±  1.645  us/op
EndToEndBenchmarks.unsampledServer_get              avgt   15  159.102 ±  3.193  us/op

Marshaling up front:
EndToEndBenchmarks.traced128Server_get              avgt   15  201.900 ±  9.384  us/op

Deferred Marshaling:
EndToEndBenchmarks.traced128Server_get              avgt   15  198.209 ±  4.196  us/op
```

**Comment by adriancole** [comment]
The above example records 2 spans, so there's overhead in low tens of microseconds per span.

There's no point in refactoring the existing async reporter, as the above deferred marshaling change was quite a lot of code. It isn't worth it for a small change. 

The async reporter needs to be completely rewritten to get above where we are at. It might be smarter to rewrite it at Brave's level as doing so could eliminate some lock contention and/or GC thrash around span updates.

**Comment by adriancole** [comment]
whoops dirty workspace. Ignore my previous comments.

**Comment by adriancole** [comment]
ignoring my other comment.. deferring is certainly worth doing, independent of this issue, which I've retitled to making things disruptor based https://github.com/openzipkin/zipkin-reporter-java/pull/84

**Comment by adriancole** [comment]
The related change out in zipkin-reporter 2.2 had much more impact in benchmark vs microbenchmark. Here's an example https://github.com/spring-cloud/spring-cloud-sleuth/pull/808

**Comment by tramchamploo** [comment]
Well, I don't see any size restriction or overflow strategy in disruptor. So maybe using disruptor before `ByteBoundedQueue` layer, or reimplement it to behave just like a ringbuffer?

**Comment by adriancole** [comment]
@tramchamploo I'm flexible, but before we make our own want to check something...

@mjpt777 are you aware of any size-based or otherwise bounded disruptor? We have means to calculate the size per item of things and would want to drop if what's currently unprocessed is at or above that

**Comment by mjpt777** [comment]
@adriancole In what dimensions are you referring to when you mention a "bounded disruptor"? Is this bounded backlog of items, or bounded size of individual entries, or some other bound? I think you are referring to bounded record size but want to be sure.

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> In what dimensions are you
> referring to when you mention a "bounded disruptor"? Is this bounded
> backlog of items, or bounded size of individual entries, or some other
> bound? I think you are referring to bounded record size but want to be sure.
>
yes so this would be the backlog. currently we have two (both) bounds,
maximum count or records and total size of records in the backlog. the
records are not uniform size.

**Comment by mjpt777** [comment]
If you are bounding in both backlog and record size then best to do that by limiting the overall bytes. There are a number of structures in [Agrona](https://github.com/real-logic/agrona) for one-to-one and many-to-one ring buffers, and a broadcast buffer for one-to-many. You could also consider [Aeron](https://github.com/real-logic/aeron) as it gives the best throughput and latency and can bound in both dimensions plus can can use in with shared memory or over the network. Aeron has many more useful features for this type of need with control over flow and congestion control if you are willing to investigate.

**Comment by adriancole** [comment]
Thanks for the tips! Both are worth exploring.

**Comment by tramchamploo** [comment]
Another choice is [http://jctools.github.io/JCTools/](JCTools) used by Netty.

**Comment by adriancole** [comment]
note: census uses a disruptor (they don't check bounds) it is prior art to consider

https://github.com/census-instrumentation/opencensus-java/blob/master/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java

I would caution that there have been a lot of small bugs about CPU which hopefully most are gone now. https://github.com/census-instrumentation/opencensus-java/search?q=disruptor&type=Issues

**Comment by adriancole** [comment]
ps anything like this should be carefully reviewed to not cause more support issues than it solves. Multiple folks should ok the impl in a way they are happy to help support bugs in it.
