### ISSUE TITLE
AsyncReport uses Kafka to send span, resulting in CPU high speed in high concurrency, resulting in request congestion

### ISSUE THREAD

**Issue by wgb1990** [openzipkin/zipkin-reporter-java#94]
1.Process CPU consumption
![image](https://user-images.githubusercontent.com/7124162/35373714-ba883788-01da-11e8-9f9d-bb26a44f0248.png)
2.Thread time-consuming
![image](https://user-images.githubusercontent.com/7124162/35373837-4ebc7fc2-01db-11e8-9306-a01157685094.png)
3.Thread stack message 
![image](https://user-images.githubusercontent.com/7124162/35379744-12ba6c2a-01f2-11e8-996d-ab328fdacdb4.png)

**Comment by wgb1990** [comment]
Sorry, the problem has been found. It was caused by too long messagetimeout time.

**Comment by wgb1990** [comment]
@adriancole In the high concurrency by adjusting the queuedMaxBytes, messageMaxBytes, messageTimeout, closeTimeout these parameters to improve the transmission performance, you can give a suggestion, thank you!

**Comment by adriancole** [comment]
Thanks for the advice
