### ISSUE TITLE
Add instructions for scribe

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-reporter-java#95]
@oscerd mentioned that camel-zipkin still has a default transport of scribe, which is sends spans as v1+thrift+base64 encoded log entries in the category "zipkin"

At the very least, we should have manual instructions for how to use the v1 reporter. Better could be to find a way to reintroduce the v1 scribe transport with the least tech debt.

**Comment by adriancole** [comment]
One way could be to add a V1 adapter, which would let us re-use the old v1 code in libraries that accept v2 spans.

```java
delegate = // io.zipkin.reporter:zipkin-reporter:jar:1.1.2
v2Reporter = new Reporter<zipkin2.Span>() {
        @Override public void report(zipkin2.Span span) {
          // shade this internal type
          reporter.report(brave.internal.V2SpanConverter.toSpan(span));
        }

        @Override public String toString() {
          return "ReporterAdapter{" + reporter.toString() +"};
        }
      };
```

**Comment by oscerd** [comment]
Yes, we are currently using brave-spancollector-scribe. 

This is the issue raised in our JIRA

https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-12214

**Comment by adriancole** [comment]
I will make a special-case for camel, as most other library maintainers have long since updated their code to not require scribe, or don't use this code to achieve that. ex finagle has a historical implementation of scribe.. to the best of my knowledge they are the only ones besides camel that still offer the option by default. I've raised an issue there to address that.

In the mean time it is a very bad idea to push users still to scribe. It isn't naturally load-balancable, people can't inspect the data that's sent, it has no portability bridges to other tracing products.. just a very bad idea. I opened this issue to please stop this https://issues.apache.org/jira/browse/CAMEL-12276

If we get more routine requests around scribe, we can help them copy-paste a workaround, too

**Comment by adriancole** [comment]
looks like camel is going to consider deprecating. finagle have also and there is no plans for new installs. For now, going to close the issue as it helps build pressure for folks to update to more supportable platforms.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-reporter-java/pull/113 re-adds scribe
