### ISSUE TITLE
High memory usage of Zipkin Reporter when Zipkin Server is unavailable

### ISSUE THREAD

**Issue by sumitsarkar** [openzipkin/zipkin-reporter-java#96]
I have been trying to use Zipkin reporter for a Spring application. I run the application on very little memory  and there is a possibility that the Zipkin server may be unavailable from time to time. During that phase the spans get dropped and remain undelivered. Since they queue up in the memory, the memory usage by the client keeps going high. 

I can see a method `onePercentOfMemory()` which porbably limits the number of spans that remain in memory before they are flushed. Is there a way I could configure the `BoundedAsyncReporter` to use even lesser memory or maybe use a custom AsyncReporter?

**Comment by adriancole** [comment]
on the README, there's a parameter: queuedMaxBytes that controls this. It is also available in the beans property.

https://github.com/openzipkin/zipkin-reporter-java#tuning

If you are directly connecting to a server and you expect it to be down regularly, yeah decrease that maybe to 5MiB or so. In general, it isn't expected to routinely take down the zipkin system
